ICC4C: Binder
Binder abstract
Classes
struct Arguments
struct Buffer
Public Member Functions
virtual Error process (const Arguments &args)=0
template<typename T >
Error operator() (T &t)
template<typename T >
Error operator() (const T &t)
Detailed Description
The binder interface. Due to the customer's requirement, some code might be activated or deactivated at runtime. This is done by changing the current instance of which binder to use. This is as fast as a pointer to function, but can carry additional data like parameters
Member Function Documentation
operator()() [1/2]
Error operator() (const T & t) inline
Some sugar implementation
References process().
operator()() [2/2]
Error operator() (T & t) inline
Some sugar implementation
References process().
process()
virtual Error process (const Arguments & args) pure virtual
The process interface that subclass will overload for their specific tasks
Implemented in CommandParser.
Referenced by operator()().